### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PaytmChecksum' not found in /var/www/html/wp-recharge/wp-content/plugins/paytm-payments/class.paytm.php:240

### ISSUE THREAD

**Issue by BiswasSuman** [paytm/Paytm_Woocommerce_Plugin#1]
Fatal error: Uncaught Error: Class 'PaytmChecksum' not found in /var/www/html/wp-recharge/wp-content/plugins/paytm-payments/class.paytm.php:240 Stack trace: #0 /var/www/html/wp-recharge/wp-content/plugins/paytm-payments/class.paytm.php(165): WC_paytm->generate_paytm_form(17) #1 /var/www/html/wp-recharge/wp-includes/class-wp-hook.php(288): WC_paytm->receipt_page(17) #2 /var/www/html/wp-recharge/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #3 /var/www/html/wp-recharge/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /var/www/html/wp-recharge/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action('woocommerce_rec...', 17) #5 /var/www/html/wp-recharge/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/var/www/html/w...') #6 /var/www/html/wp-recharge/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(201): wc_get_template('checkout/order-...', Array) #7 /var/www/html/wp-recharge/wp-content/plugins/woocommerc in /var/www/html/wp-recharge/wp-content/plugins/paytm-payments/class.paytm.php on line 240

**Comment by nitingamiotechnologies** [comment]
I found the same issue, Please fix it

**Comment by chandrashekhar-garsari** [comment]
@BiswasSuman and @nitingamiotechnologies . Sorry You are facing issue. Please do some steps 
=> download the latest version of plugin and install it.
=> Check if there is any other plugin installed related to Paytm, This might create conflict .

If issue still persist please raise an email to cmt.ops@paytm.com .

**Comment by abpaytm** [comment]
Fixed closed
