### ISSUE TITLE
Wordpress 5.5.1 compatibility test

### ISSUE THREAD

**Issue by zxcV32** [paytm/Paytm_Woocommerce_Plugin#4]
Can you please test and mark this plugin to be compatible with the latest version of **Wordpress Version 5.5.1** and **Woocommerce version 4.6.0**.

**Comment by chandra-garsari** [comment]
Yes, This plugin is compatible with the latest version of Wordpress Version 5.5.1 and Woocommerce version 4.6.0.

Thanks!
