### ISSUE TITLE
Scripts are loading on every page? 

### ISSUE THREAD

**Issue by naveenrnimmala** [paytm/Paytm_Woocommerce_Plugin#7]
V2 causes render blocking on page load. Why do we need paytm scripts on every page of the site, it should load only on checkout page. Can you look into it pls? My google pagespeed is low because of this.
@LalitChaudhary1

**Comment by naveenrnimmala** [comment]
Update: Made the following changes on my install to stop it from loading on other pages.

function paytmWoopayment_blinkcheckoutScript() {
	**if ( is_woocommerce() or is_cart() or is_checkout() ) {**
	$settings = get_option( "woocommerce_paytm_settings" );
	$checkout_url          = str_replace('MID',$settings['merchant_id'], PaytmHelper::getPaytmURL(PaytmConstants::CHECKOUT_JS_URL, $settings['environment']));
   echo '<script type="application/javascript" crossorigin="anonymous" src="'.$checkout_url.'" async></script>';
**}**
}
add_action('wp_head', 'paytmWoopayment_blinkcheckoutScript');

**Comment by abpaytm** [comment]
Hi,
we have updated our plugin  .Now this issue has been resolved .  If still any issue please mail on cmt.ops@paytm.com
