### ISSUE TITLE
Woocommerce 5 

### ISSUE THREAD

**Issue by naveenrnimmala** [paytm/Paytm_Woocommerce_Plugin#8]
Updated Woo to 5.0 and the checkout screen was stuck on Paytm Loading ...
This was with the Jan 19 and Feb 4 builds.. Had to revert to Dec 10 release to enable checkout.

**Comment by elschatteler** [comment]
Jan 19 build is working fine for WC5.0. Feb 4.0 build have issues so does the wordpress plugin.

**Comment by naveenrnimmala** [comment]
I had issues with wordpress release v2.2 also. Not sure if it's the plugin or my setup. I'll keep using Dec 10 build for now. Thank you. Glad to see you update the official WP plugin, it would be better if you can update change logs there and be available to answer queries there under support section.

**Comment by abpaytm** [comment]
Hi,
we have updated our plugin with latest JS Checkout .You can get the latest plugin from wordpress plugin directory also .  If still any issue please mail on cmt.ops@paytm.com
